services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
      - gradle-cache:/root/.gradle
    command: ./gradlew build --no-daemon --stacktrace

volumes:
  gradle-cache: