services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    command: ./build-and-sign.sh

volumes:
  gradle-cache: